kind: Service
apiVersion: v1
metadata:
  name: "movementregistrationservice"
spec:
  selector:
    app: "movementregistrationservice"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movementregistrationservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movementregistrationservice
    spec:
      containers:
        - name: movementregistrationservice
          image: "carlotheunissen/movementregistrationservice:latest"
          imagePullPolicy: Always
          env:
            - name: environment
              value: "production"
          resources:
            requests:
              memory: "40Mi"
              cpu: 0.1
            limits:
              memory: "500Mi"
              cpu: 0.5
          ports:
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /deploy/v1/health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /deploy/v1/health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 20
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: movementregistrationservice
spec:
  #scaleRef:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: movementregistrationservice
    #subresource: scale
  minReplicas: 2
  maxReplicas: 5
  #cpuUtilization:
    #targetPercentage: 70
  targetCPUUtilizationPercentage: 40