apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3307
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db
subsets:
  - addresses:
      - ip: 192.168.0.100
    ports:
      - port: 3307